### ISSUE TITLE
affe & going to line

### ISSUE THREAD

**Issue by mclearc** [minad/affe#17]
This is a weird bug (if it is a bug in affe and not my config): Sometime in the last few groups of commits i've stopped being able to go to a line search in affe-grep using `RET`. Also, the preview function doesn't work any longer even though I have `  (setq consult-preview-key (kbd "C-f"))` in my consult config. Any sense of what might be going wrong here? I've put my config below. Note that I've tried this with `emacs -Q` and have the same problem. 

```emacs-lisp
(use-package affe
  :straight (affe :type git :host github :repo "minad/affe")
  :commands (affe-grep)
  :after (orderless)
  :config
  ;; Orderless settings
  (defun affe-orderless-regexp-compiler (input _type)
    (setq input (orderless-pattern-compiler input))
    (cons input (lambda (str) (orderless--highlight input str))))
  (setq affe-regexp-compiler #'affe-orderless-regexp-compiler))
```

**Comment by mclearc** [comment]
Perhaps I should add that I can go to a line searched in affe using `embark-consult-goto-grep` but formerly all I had to do was press `RET`, no embark command required. Perhaps this may be due to some configuration I have in consult or embark? I use the vertico-consult-embark-orderless ecosystem, but perhaps some update has changed how affe interacts with these?

**Comment by minad** [comment]
Thanks! I refactored the grep infrastructure in Consult heavily and missed a change in affe. Should be fixed now.
