### ISSUE TITLE
Support on tramp buffer

### ISSUE THREAD

**Issue by tshu-w** [minad/affe#25]
If I run affe-* on tramp buffer, I got `Buffer * has no process`.
```emacs-lisp
(use-package affe
  :straight t
  :defer t
  :config
  (with-eval-after-load 'orderless
    (defun affe-orderless-regexp-compiler (input _type)
      (setq input (orderless-pattern-compiler input))
      (cons input (lambda (str) (orderless--highlight input str))))
    (setq affe-regexp-compiler #'affe-orderless-regexp-compiler)))
```

GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2021-11-01

**Comment by minad** [comment]
Affe cannot work on tramp buffers. It does not support searching on the remote system.

**Comment by tshu-w** [comment]
Hi, I wonder what are the limitations of affe compared to consult-grep, which support tramp file.

**Comment by minad** [comment]
We can probably make it work by setting a tramp handler in the affe-backend.el.

**Comment by minad** [comment]
Closing. PR welcome which adds Tramp support. But Tramp doesn't work well with the current affe model - too much data will be transferred except if we run the filter backend on the server itself. This needs dedicated support in affe for Tramp.
