### ISSUE TITLE
A error after upgrading consult

### ISSUE THREAD

**Issue by linwaytin** [minad/affe#27]
The functions `affe-find` and `affe-grep` show error 
``` elisp
Error running timer 'consult--async-aftere-change` .....
```
The detail is shown in this [screenshot](https://i.imgur.com/Yftq0Xv.png).

**Comment by minad** [comment]
I don't see this error. Please ensure that all packages are upgraded.

**Comment by linwaytin** [comment]
My emacs version is `27.2`, and both `consult` and `affe` are the newest versions on Melpa.

The issue persists on `emacs -Q` with only `consult` and `affe`.

**Comment by minad** [comment]
Alright, thanks! Should be fixed by 0b96f2c3b1a80b488b6611f75d4aebbdf7d0bffe.

**Comment by linwaytin** [comment]
Yes, the issue is gone. Thanks for the quick fix!
