### ISSUE TITLE
affe-grep preview doesn't work

### ISSUE THREAD

**Issue by chasecaleb** [minad/affe#29]
Hi, I just started using affe and I can't get grep previews working, even though the readme says previews should be enabled automatically.

Here's a minimal reproduction:

1. Create `/tmp/affe-test.el` containing:
    ```emacs-lisp
    ;;; -*- lexical-binding: t -*-
    (require 'consult)
    (require 'vertico)
    (require 'affe)
    (vertico-mode)
    ```
1. Run emacs: `emacs -Q --load /tmp/affe-test.el`
1. M-x affe-grep -> search for something. Preview doesn't happen.
1. M-x consult-grep -> search for something. Preview works.

**Comment by minad** [comment]
I cannot confirm this. Both `affe-grep` and `consult-grep` preview work for me on Emacs 28. Maybe there is something wrong with the package versions you used, your packages are not installed properly, or your recipe misses some steps.

**Comment by chasecaleb** [comment]
Oops, I meant to put what revisions I'm using. Sorry! I'm building from github sources, with the following revisions:

* Vertico: a92b1e47ffe343e2c3096e2ea61af013a8a02af9
* Consult: 47c4f405efdf4692c6b7e1dd2098573db9aeae6c
* Affe: 36d8654a8d7e862d2e64f6bece370e664218ab1a

These were all the latest `HEAD`s as of yesterday. Does that make a difference?

If you want I can figure out what revisions are currently published to ELPA/MELPA and try with those.

**Comment by minad** [comment]
I am also on the lastest commits, so this shouldn't change anything. I don't know what is wrong on your setup. Note that `affe-grep` relies on the same machinery as `consult-grep` for preview, this shouldn't change anything. I am not sure which particular detail of your setup leads to issues here? Does `consult-ripgrep` work for you? Maybe you use a ripgrep configuration file? It may make sense to specify `--no-config` in `consult-ripgrep-args` and `affe-grep-command`.

**Comment by minad** [comment]
Generally I recommend to stick with `consult-ripgrep` which is the more robust command. It is more widely used so it is more likely to work in special scenarios. Affe works well for me but has known issues, e.g., I've heard that it doesn't work on Windows. Furthermore by construction, Affe cannot work well on larger projects due to how filtering is implemented. Nevertheless I hope that you are able to figure out what detail of your setup affects Affe negatively here. As long as I am unable to reproduce the problem I cannot do anything.

**Comment by chasecaleb** [comment]
> As long as I am unable to reproduce the problem I cannot do anything.

Trust me I get that! No problem. I'll update this issue if I figure out what's going on. Have some other things going on that I need to do first though, so it may be a while. Otherwise I may use `consult-ripgrep` instead.
