### ISSUE TITLE
[MacOS] `grep` and `find` commands are run in the user's home folder, rather than the current / project folder

### ISSUE THREAD

**Issue by rajk04** [minad/affe#3]
Hi!

Thanks for creating this! I'm running into some issues with the commands, as the `grep` and `find` operations are being performed on my home directory, rather than the current / project directory. I'm probably missing something obvious here. Is there some place where I can start debugging this?

---

I could replicate this with two configurations, on a macOS system running emacs 28:
- Using straight (results surfaced using `selectrum`)
```elisp
  (use-package affe
    :straight (:host github :repo "minad/affe" )
    :after (orderless consult)
    :custom (
             (affe-regexp-function #'orderless-pattern-compiler)
             (affe-highlight-function #'orderless-highlight-matches)
             (affe-find-command "fd"))
    :config
    ;; Manual preview key for `affe-grep'
    (setf (alist-get #'affe-grep consult-config) `(:preview-key ,(kbd "M-."))))
```
- Following the instructions you wrote up in https://github.com/minad/affe/issues/1#issuecomment-844903933 (results surfaced using `icomplete-vertical`)

**Comment by minad** [comment]
> I'm running into some issues with the commands, as the grep and find operations are being performed on my home directory, rather than the current / project directory.

Oh, that's weird. You can check the default-directory of the Emacs process which runs async-backend.el.

**Comment by minad** [comment]
Can you reproduce this without straight?

**Comment by rajk04** [comment]
> Can you reproduce this without straight? 

Yep! I moved the files over to a different directory, and loaded it manually.

> Maybe it has also something to do with the Emacs on Mac.

That seems likely. I'll try it on a different system and see if any variables are set differently.

Thanks for bearing with me on this!

**Comment by mclearc** [comment]
I'm seeing a similar problem. Using macOS 10.15.7, emacs 28

**Comment by minad** [comment]
I just tested Emacs 28. For me it works with both 27 and 28 on Linux. I think there was some Mac-specific default-directory issue also in Consult.

**Comment by rajk04** [comment]
Dug in a little more here, and created a new emacs process using:

```elisp
         (call-process
          (file-truename
           (expand-file-name invocation-name
                             invocation-directory))
          nil nil nil "-Q")
```

The `default_directory` is reported as `~/emacs_testbed` in the parent process, and `~` in the child process. I guess it's some macOS specific behavior

**Comment by minad** [comment]
Yes the slash is missing from the directory, then it will fail on mac. Someone should report that upstream via `report-emacs-bug`. See https://github.com/minad/consult/issues/108.

**Comment by rajk04** [comment]
@minad sorry, that's my mistake. I've updated both paths to include the slashes.

**Comment by rajk04** [comment]
I'll report the difference in behavior between linux and mac.

One other dot: It's possible to pass along the current directory to an emacs child process using `--chdir=DIRECTORY_NAME` [1]. Shall I make a PR to pass along with directory information to the subprocess?

[1] https://www.gnu.org/software/emacs/manual/html_node/emacs/Initial-Options.html

**Comment by minad** [comment]
Yes please go forward with the bug report and the PR.

**Comment by hmelman** [comment]
I haven't used affe yet and don't understand this issue but as a mac user it made me think of three things I'll throw out:
- something should use `file-name-as-directory`
- There was an emacs bug about mac and default-directory, https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44446
- When starting emacs on a mac by double clicking the app icon the users environment variables are not inherited (or something like that).  It typically shows up with `exec-path` but not exclusively.  It may be different in the macport.  There is the package `exec-path-from-shell.el` to deal with this.
