### ISSUE TITLE
affe-find stops working after latest consult update

### ISSUE THREAD

**Issue by s-kostyaev** [minad/affe#30]
It shows search results as candidates, but on press `<RET>` minibuffer disappears without file opening
![output-2022-04-08-22:11:34](https://user-images.githubusercontent.com/8576745/162471127-c254cbd9-545d-4f28-b246-d2ac0773605c.gif)
Latest versions from MELPA

**Comment by minad** [comment]
I cannot confirm this. Are you sure that you updated both Consult and Affe?

**Comment by minad** [comment]
Also make sure that you use the newest version since there have been a few issues with my breaking change. But it should be fine now.

**Comment by s-kostyaev** [comment]
This is something from my configuration. Can't reproduce it with `emacs -Q`
Thank you.

**Comment by s-kostyaev** [comment]
Looks like this issue relates to native compilation. I have changed my configuration and undo it and now all works fine.

**Comment by minad** [comment]
It could be that it was an update issue. I've observed before that native compilation has issues when compiling packages and replacing functions asynchronously (not related to affe but other packages). But then you should also see errors in the Messages buffer. Maybe `native-comp-deferred-compilation=nil` helps. I have to investigate this at somepoint.

**Comment by Ghosty141** [comment]
I have the same issue! Also running consult but setting native-comp-def... doesnt help sadly

**Comment by s-kostyaev** [comment]
@Ghosty141 try to clean native compilation cache

**Comment by Ghosty141** [comment]
I deleted the eln-cache folder, set native-comp-deferred-compilation to nil (setq ... nil) and ran package-install affe. Sadly it still doesn't work.

**Comment by s-kostyaev** [comment]
Try it with `emacs -Q`

**Comment by Ghosty141** [comment]
You mean emacs -Q -> add MELPA -> package install consult -> package install affe -> check if affe find works?

**Comment by s-kostyaev** [comment]
You can do it like this. Or you can skip installing step, just initialize package, load affe and try affe-find.

**Comment by Ghosty141** [comment]
It really seems to be a config issue. With the following init.el it worked:

```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(setq use-package-always-ensure t)
(use-package consult)
(use-package affe)
```

What did you change about your configuration that solved the problem?

**Comment by s-kostyaev** [comment]
> What did you change about your configuration that solved the problem?

Looks like it doesn't matter. What matters is rebuilding my init.el compiled cache.
