### ISSUE TITLE
[Question] Example of using find with multiple directories?

### ISSUE THREAD

**Issue by jojojames** [minad/affe#32]
Trying to do something like this:

```
find ~/.emacs.d/ ~/Code -name emacs
/Users/james/.emacs.d//straight/repos/password-store/contrib/emacs
/Users/james/.emacs.d//straight/repos/otp/lib/tools/emacs
/Users/james/.emacs.d//straight/repos/gocode/emacs
/Users/james/Code/go/src/github.com/nsf/gocode/emacs
/Users/james/Code/emacs
/Users/james/Code/emacs/test/manual/etags/el-src/emacs
/Users/james/Code/emacs/test/manual/etags/c-src/emacs
/Users/james/Code/emacs/doc/emacs
/Users/james/Code/emacs/src/emacs
/Users/james/Code/emacs-mac/test/etags/el-src/emacs
/Users/james/Code/emacs-mac/test/etags/c-src/emacs
/Users/james/Code/emacs-mac/doc/emacs
```

I was looking at modifying affe-find-command but not super sure what the right incantation it'd be to do a similar command. I've tried tracing the code a little and could use a pointer, thanks!

Trying to play around with the find command itself in zsh gives me an error  (though I assume I'm doing something obviously wrong) ->

```
find -not ( -wholename */.* -prune ) -type f
-> find ~/.emacs.d/ ~/ -not ( -wholename */.* -prune ) -type f -name test
```

**Comment by minad** [comment]
If you manage to use find to search multiple directories in zsh then it should also work in affe. As far as I know affe doesn't pass the directory to the command currently and just executes the backend in the default-directory.

**Comment by Ghosty141** [comment]
I had similar problems with find (getting excluding directories to work) but switched to rg which worked perfectly for me.

**Comment by jojojames** [comment]
> If you manage to use find to search multiple directories in zsh then it should also work in affe. 

I set something like this:
(setq affe-fine-command "find ~/.emacs.d/ ~/Code -name")

Run M-x affe-find in *scratch* buffer and continue to get find results from directories under ~/.

If I run ```find ~/.emacs.d/ ~/Code -name config``` in ~/, I get back results only from ~/.emacs.d and ~/Code.

> I had similar problems with find (getting excluding directories to work) but switched to rg which worked perfectly for me.

Could you post up an example? I'd be happy to try it out and report back.

**Comment by minad** [comment]
@jojojames I think the problem here is that you have to expand the paths, since the command will not be passed through the shell.

**Comment by jcguu95** [comment]
@jojojames here's my workaround for this problem. I have three folders that contain books and slides. To use `affe-find` to list all of them, I first symlink the folders to a temporary foler, and search in that directory.

```
  (defun my/search-readings ()
    (interactive)
    (let* ((libs '("/tmp/readings/" "/Users/jin/data/capture/+media/"
                   "/Users/jin/.+PLUGS/storage-local/readings/"))
           (root "/tmp/search-readings/")
           (dummy (files--ensure-directory root))
           (buf (current-buffer))
           (default-directory (f-join root (org-id-uuid)))
           (affe-find-command "rg --color=never --follow --files"))
      (declare (ignore dummy))
      (files--ensure-directory default-directory)
      (cl-loop
       for lib in libs
       do (make-process
           :name     "find books"
           :command  `("ln" "-sf" ,lib)
           :buffer   (get-buffer "*Messages*")
           :sentinel (lambda (proc type)
                       (declare (ignore (proc type)))
                       (with-current-buffer buf
                         (revert-buffer)))))
      (affe-find)))

  (map! :map global-map
        "<f9>" #'my/search-readings)
```
