### ISSUE TITLE
How do I open multiple files at once?

### ISSUE THREAD

**Issue by Ghosty141** [minad/affe#34]
Hi, like the title says I'm wondering how I can open multiple files at once. For example: When searching for "foo cpp" (with orderless) and there are both "foo.cpp" as well as "foobar.cpp".

**Comment by minad** [comment]
Usw embark

**Comment by Ghosty141** [comment]
Ah I see (embark-act-all seems to do what I want). With find-file and vertico you can use M-RET to do this, is there a reason why affe doesn't handle it the same way/what would you think of a PR for this feature?

**Comment by minad** [comment]
find-file has a special behavior if you press M-RET (submit the prompt). In that case the wildcards of the input are expanded and all the matching files are opened. But this is not necessarily the same set as the files shown by completion.

**Comment by Ghosty141** [comment]
Oh I see, well then I guess using embark is probably the best choice. I'll just make a keybind for M-RET to call embark-act-all -> enter in the affe mode map. Thanks 👍
