### ISSUE TITLE
affe-find and affe-grep hangs emacs

### ISSUE THREAD

**Issue by toniz4** [minad/affe#35]
I'm running GNU Emacs 28.1, with native compilation enabled.
When running the following configuration with emacs -Q, this can be achived with the following config:
```elisp
(require 'package)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package consult
 :ensure t)

(use-package affe
 :ensure t)
```

When running `affe-find` or `affe-grep` the ui freezes untill I press C-g. No logs buffer are displayed.

Tried running affe-find with ripgrep or with the default  find, with no sucssess.

**Comment by terlar** [comment]
I also experience the same issue, was planning to evaluate this package but every time I came back to test it I run into this problem. At least now I know I'm not the only one.

**Comment by minad** [comment]
This doesn't happen for me on 28, Linux/X11. Anyway I recommend to just use consult-grep/ripgrep which are as good (or even better for large projects).

**Comment by minad** [comment]
Do you still observe this issue? I close this due to inactivity. Affe works well for me but you may want to use the Consult commands anyway.
