### ISSUE TITLE
`affe-find-command` with pipes

### ISSUE THREAD

**Issue by jcguu95** [minad/affe#36]
I'd like to make `affe-find-command` to include pipes. For example,

```
(affe-find-command "fn () { rg --color=never --follow --files | rg --color=never '.*pdf$' ; } ; fn")
```

Turns out this is fine, though it didn't act as expected. Instead of listing all files ending with `pdf`, it lists nothing. Are there any workarounds?

**Comment by minad** [comment]
Sorry for the late response. This does not work since the input string is split and treated directly as a command line. You would have to wrap the entire command by `sh -c "..."`. Does this help?

**Comment by jcguu95** [comment]
Thank you for your response, and I apologize for any inconvenience. I was hoping you could help me understand a bit more about the following statement:

> since the input string is split and treated directly as a command line.

If you have any additional information or alternative methods to improve composability, I would greatly appreciate it if you could kindly share them with me. Thank you very much for your time and assistance.

**Comment by minad** [comment]
The pipes are implemented in the shell but affe invokes the command line string directly. Therefore you have to manually wrap with sh -c.

**Comment by jcguu95** [comment]
I see. Thank you!

For those who are interested, here's what worked for me

```
(let ((affe-find-command
       "sh -c \"
fn () {
  rg --color=never --follow --files |
  rg --color=never '.*(?:pdf|epub|djvu)$'
}
fn
\""))
  (affe-find)) 
```

This searches for all files that end with `pdf`, `epub`, or `djvu`. :)

**Comment by ave-63** [comment]
I wanted to add my own solution here in case someone needs it. My goal is to make affe present files in a certain directory (/home/ben/nxc/Courses/) at the top of the list, and files that have `cache` in their path at the bottom of the list. I used awk and sort to sort them this way.

 The `sh -c` didn't work for me but it did work when I put my command in a script:

`#!/bin/bash

fd -H -a --color=never -p "$@" | \
awk '{if ($0 ~ "/home/ben/nxc/Courses/") print "1" $0; \
else if ($0 ~ /cache/) print "3" $0; \
else print "2" $0}' | \
sort | \
cut -c2-`

And then `(setq affe-find-command "/path/to/script")`
