### ISSUE TITLE
preview not working with affe-find

### ISSUE THREAD

**Issue by ghosty141** [minad/affe#37]
Hi,
should preview work for affe-find too or is it only meant for affe-grep? Because with affe-find I don't get a preview of the select file.

**Comment by minad** [comment]
`affe-find` and `consult-find` don't have preview by default, since it is not so useful there I think. You can add it via `consult-customize`. Note that this relies on internals and may change.

~~~ elisp
(consult-customize consult-find affe-find :state (consult--file-preview))
~~~

**Comment by ghosty141** [comment]
Thanks, just fyi, your example use of preview-key uses the old syntax with (kbd ...) 😉

**Comment by minad** [comment]
Right, affe is not as maintained as my other packages, since it is more experimental. I recommend to use `consult-grep/find` instead which scale much better.

**Comment by ghosty141** [comment]
I'll check out consult-find I think there was reason why I used affe initially but this might've changed. Is there any advantage to affe currently? (I already use consult-grep for example)

**Comment by minad** [comment]
Affe is faster for small projects since the filtering happens in a separate process. It will also show candidates right away without input. The downside is that this doesn't scale to larger projects.

**Comment by ghosty141** [comment]
> Affe is faster for small projects since the filtering happens in a separate process. It will also show candidates right away without input. The downside is that this doesn't scale to larger projects.

I tried it at work and noticed that affe with rg as backend works faster for me compared to using consult-find with find. With affe + rg the list of candidates gets updated while typing new characters while with consult-find + find it takes too long and it stays empty until I finish typing for a short time. Can you use rg as consult-find backend?
