### ISSUE TITLE
After update consult to version 25-Feb-2003 affe-find does not work

### ISSUE THREAD

**Issue by damanis** [minad/affe#39]
Seems, after update consult to `20230225.2229`, affe-find stop work with error 'wrong parameter'. affe-find with numeric parameter still works.

**Comment by minad** [comment]
Thanks for the report. Please check if it works again.

**Comment by damanis** [comment]
I clone master - it works.
But, seems, before with numeric parameter affe-find first ask where find while now it start find in current file directory immediately.

**Comment by minad** [comment]
> But, seems, before with numeric parameter affe-find first ask where find while now it start find in current file directory immediately.

This is not true. You confused the asynchronous affe search with the CRM directory/file selection.

**Comment by vancleve** [comment]
Since this update, I'm having trouble with using `affe-find` to search my home folder. If I type `M-:` then `(affe-find "~/")` I get a list of files in the current directory of one my loaded buffers (though not necessary the currently visited buffer).
