### ISSUE TITLE
Attempt to shape unibyte text error

### ISSUE THREAD

**Issue by Alexander-Miller** [minad/affe#4]
When using `affe-grep` I sometimes see the following error:

> #<subr read-from-minibuffer>: Attempt to shape unibyte text
> sit-for: Attempt to shape unibyte text

It cancels the search and after it's happened `affe-grep` is no longer usable, whatever I search, I always see `(total=0+)`.

This error is related to the use of ligatures: https://github.com/mickeynp/ligature.el/issues/10 

I am using the latest affe pulled from git, a recently self-compiled Emacs 28, my font is Fantasque Sans Mono and my ligature config looks like this:

```Elisp
(ligature-set-ligatures
   t
   '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>" ":::"
     "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!==" "!!." ">=>"
     ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<" "<~~" "<~>" "<*>"
     "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->" "<--" "<-<" "<<=" "<<-"
     "<<<" "<+>" "</>" "###" "#_(" "..<" "..." "+++" "/==" "///" "_|_"
     "www" "&&" "^=" "~~" "~@" "~=" "~>" "~-" "**" "*>" "*/" "||" "|}"
     "|]" "|=" "|>" "|-" "{|" "[|" "]#" "::" ":=" ":>" ":<" "$>" "=="
     "=>" "!=" "!!" ">:" ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~"
     "<*" "<|" "<:" "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:"
     "#=" "#!" "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++"
     "?:" "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
     "://"))

  (global-ligature-mode)
```

**Comment by minad** [comment]
Do you have a stacktrace?

**Comment by Alexander-Miller** [comment]
Unfortunately not, it looks like the backtrace is eaten by the error as well:

> Entering debugger...
> display-buffer-below-selected: Attempt to shape unibyte text

I'll try and find the problematic ligature tomorrow.

**Comment by minad** [comment]
Hmm, but I don't see if this has really something to do with this package. The display is not really the concern of Affe, this is more of a backend thing. It could be that there is a separate issue in Affe, which is somehow overshadowed by your ligature issues. Note that the package is very new, I wrote it yesterday. If you are looking for sth solid, I wouldn't use it yet ;)

consult-ripgrep/counsel-rg/helm-rg are the more reliable alternatives for now.

**Comment by Alexander-Miller** [comment]
I think I found the culprit, looks like it's the unicode numbers in this function:

```
(pcase ,n
  (1 " ➊") (2 " ➋") (3 " ➌") (4 " ➍")  (5 " ➎") (6 " ➏")
  (7 " ➐") (8 " ➑") (9 " ➒") (10 " ➓") (_ ""))
```

They're not ligatures, so this something else. helm-ag and consult-(rip)grep have no such problem, looks like this is really a bug in affe.

Another strange part is that I wasn't directly matching those lines, I was looking for the string "se" which would've matched the "pcase". In addition if I do start a search for ` ➊")` it does not crash, I see a bunch of raw bytes instead:
![affe](https://user-images.githubusercontent.com/5951157/119091348-34510c00-ba0d-11eb-98df-a0120d85bcc2.png)

**Comment by minad** [comment]
Thanks, this sounds indeed like an encoding issue in the backend<->frontend communication. Should be easy to fix.

**Comment by tomoya** [comment]
Hi,
Today, I found affe. After that, I tried affe immediately.
I had the same problem when using affe-grep with a Japanese file whose file encoding is UTF-8.

So, as a trial, I changed the encoding to utf-8 as follows. Then, It was resolved.

```elisp
diff --git a/affe.el b/affe.el
index 2e89dd9..34307a8 100644
--- a/affe.el
+++ b/affe.el
@@ -95,7 +95,7 @@
      (lambda (&rest _)
        (unless (equal rest "")
          (funcall callback (list rest))))
-     :coding 'no-conversion
+     :coding 'utf-8
      :family 'local
      :service (expand-file-name name server-socket-dir))))
```

| `:coding 'no-conversion` | `:coding 'utf-8` |
| --- | --- |
| <img width="624" alt="Screen Shot 2021-05-26 at 20 02 00" src="https://user-images.githubusercontent.com/18009/119649982-40e6c180-be5e-11eb-969a-696a2c997f6f.png"> | <img width="580" alt="Screen Shot 2021-05-26 at 20 01 30" src="https://user-images.githubusercontent.com/18009/119649992-447a4880-be5e-11eb-841c-c7124e7f6489.png"> | 

Please try to reference. Thank you.

**Comment by minad** [comment]
Thanks, does that fix the issue if one sets the coding to utf8 everywhere? See also affe-backend--setup, there I am also using no-conversion. Is this wrong there too?

**Comment by tomoya** [comment]
According to my investigation, affe-backend--setup does not need to be changed. Only affe--connect needs to be changed.
So, I thought of two options.

1. Define a new defcustom variable affe-connect-coding-system. And set default value to utf-8 or something else.
2. Set `:coding` to `buffer-file-coding-system` variable. I think this is a good way for most people.

**Comment by Alexander-Miller** [comment]
The solutions can be combined as well: use `buffer-file-coding-system` by default, but override with `affe-connect-coding-system` if it is non-nil.

**Comment by tomoya** [comment]
That's a good idea!  want you to change it that way.

**Comment by tomoya** [comment]
I created PR that uses buffer-file-coding-system if affe-connect-coding-system is nil.
@Alexander-Miller, Thanks for your advice.

**Comment by tomoya** [comment]
@minad I updated affe and confirmed works. Thank you.
