### ISSUE TITLE
affe-grep very slow

### ISSUE THREAD

**Issue by damanis** [minad/affe#40]
[consult-grep](https://github.com/minad/consult/issues/758) has some problem in output, but finds all entries fast.
In affe-grep same find take many times.
Versions:
- GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-05-31
- affe-20230301.337 (previous version did have the problem, too)

**Comment by minad** [comment]
Affe is only fast for small projects.

**Comment by damanis** [comment]
@minad 
I opened the issue, because `rg` itself and same as affe module in nvim (with fuzzy find using `rg`) work very fast in my tree.
