### ISSUE TITLE
Buffer *scratch* has no process

### ISSUE THREAD

**Issue by abougouffa** [minad/affe#41]
Hello and thank you for this awesome package!

I'm experiencing a wired issue these days on my Emacs 30.0.50 build (I can't tell at which Emacs commit it started).

I'm this to configure Affe, which worked fine in the past:

```elisp
(use-package affe
  :straight t
  :demand t
  :config
  ;; Use orderless to compile regexps
  (defun +affe-orderless-regexp-compiler (input _type _ignorecase)
    (setq input (orderless-pattern-compiler input))
    (cons input (lambda (str) (orderless--highlight input str))))

  (setq affe-regexp-compiler #'+affe-orderless-regexp-compiler)

  ;; Manual preview keys
  (consult-customize affe-grep :preview-key (kbd "M-p"))
  (consult-customize affe-find :preview-key (kbd "M-p")))
```

And when calling `affe-grep` or `affe-find`, I get nothing but a message saying (supposing the current buffer is *scratch*):

```
Buffer *scratch* has no process
```

I've tried to add `(setq debug-on-message "Buffer .* has no process")` in my `init.el` to try to catch the problem, but the `affe-*` still display the message and without triggering the debugger!

Any insights to how I can fix this?

**Comment by minad** [comment]
Can you please try to reproduce this first in a minimal configuration or with Emacs 29? I cannot yet support Emacs 30 which is unstable. Anyway, my recommendation is to use consult-grep which is more robust.

**Comment by jneidel** [comment]
Just for future reference:
I had the same error on this code

```elisp
(use-package affe
  :bind (("M-F" . affe-find) ; in cwd
         ("M-f" . (lambda () (interactive) (affe-find "/home/jneidel"))))
```
- M-F worked
- M-f only worked on linux, not on macos (thats where I got the error)

Fix was using $HOME instead of hardcoded linux home directory.
```elisp
(use-package affe
  :bind (("M-F" . affe-find) ; in cwd
         ("M-f" . (lambda () (interactive) (affe-find (substitute-in-file-name "$HOME")))))
```
