### ISSUE TITLE
`affe-grep` doesn't work with Posix `grep`

### ISSUE THREAD

**Issue by fuzy112** [minad/affe#43]
It seems that `grep -r --exclude-dir=.* ^$`  will exclude the path if the path itself is `.`.

**Comment by minad** [comment]
I don't see any issue. Can you please provide the exact steps or even suggest a possible fix?

**Comment by fuzy112** [comment]
The root cause is that the default value of `affe-grep-command`
```elisp
(defcustom affe-grep-command
  (cond
   ((executable-find "rg") "rg --null --color=never --max-columns=1000 --no-heading --line-number -v ^$")
   (t "grep -I -r --exclude=.* --exclude-dir=.* --null --color=never --line-number -v ^$"))
  "Grep command."
  :type 'string)
```
contains `--excluder-dir=.*`, which excludes `.` as well.

**Comment by minad** [comment]
This seems like a bug in grep (or the posix spec) actually, since `.` is not the "true" name of the directory. We can probably use more specific exclude regexps to prevent the issue? Something like `--exclude-dir=.[a-z]*`.

**Comment by minad** [comment]
Feel free to experiment, but I decided to close this issue as wontfix for various reasons:

- consult-ripgrep is preferable over affe-grep
- You can use rg instead of grep
- You can use GNU grep instead of "Posix" grep, whatever Posix grep is in your case. Mac? Bsd?

**Comment by fuzy112** [comment]
> We can probably use more specific exclude regexps to prevent the issue?

Of course, I personally use `grep-find-ignored-directories`.  But I think it's strange to leave a package unusable by default.


> * You can use GNU grep instead of "Posix" grep, whatever Posix grep is in your case. Mac? Bsd?

GNU grep has the same issue as well.  I said "Posix" grep because the README.org says 

> If rg is not available, the usual Posix find and grep utilities are used instead.

which made me thought `affe` only supports Posix emacs. So I also tested it with `POSIXLY_CORRECT=1`.

**Comment by minad** [comment]
I see. For now I dropped grep support, rg is required now. I have rg on my systems therefore I usually don't invoke the alternative commands.
