### ISSUE TITLE
 I get error when running affe-find 

### ISSUE THREAD

**Issue by x0xntor33alx0x** [minad/affe#44]
**the error is:** Error running timer ‘consult--async-after-change’: (wrong-number-of-arguments #<subr consult--default-regexp-compiler> 3)
**consult version:** 20230326.2048
**affe version:** 20230314.1552
**emacs version:** GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, cairo version 1.16.0) of 2022-01-01

**Comment by x0xntor33alx0x** [comment]
yes.

**Comment by minad** [comment]
I think something wasn't updated correctly, since a `consult--async-after-change` function doesn't exist anymore in Consult. But there is a `consult--async-after-change-hook` function.
