### ISSUE TITLE
Affe find doesn't list hidden files and files under hidden directories

### ISSUE THREAD

**Issue by sooriravindra** [minad/affe#45]
```
Welcome to the Emacs shell

~/repos/DotFiles $ ls -a vim/.vimrc 
vim/.vimrc

---------------------------------------
!/0    Fuzzy find (Project DotFiles) (total=1) : vimrc [Match required]
```

As can be seen from above the search fails for hidden files. Is there a configuration variable to allow searching hidden files?

**Comment by minad** [comment]
You can configure affe-find-command and affe-grep-command. See the rg manual for appropriate options.

**Comment by sooriravindra** [comment]
Thank you for the swift response.

**Comment by axelknock** [comment]
Fairly dirty but effective if you want to only conditionally search for hidden files/add arguments (which aligns with behavior of consult-ripgrep conditionally ignoring .gitignore when invoked to search directory instead of project).

``` emacs-lisp
(setq affe-find-command "fd ")
(setq affe-find-command-appended-arguments "-H")
;; (setq affe-find-command-appended-arguments "--hidden") ;; ripgrep
(defun affe-add-arguments (&optional arg)
  (interactive "P")
  (when arg
    (setq-local affe-find-command
                (concat affe-find-command
                        affe-find-command-appended-arguments
                        " "))))
(advice-add 'affe-find :before #'affe-add-arguments)
```
