### ISSUE TITLE
affe-grep find lines aren't included search pattern

### ISSUE THREAD

**Issue by damanis** [minad/affe#46]
Last `affe` module from elpa. Configuration taken from `affe` github page (with orderless).
`affe-find-command` is default: 
```rg --null --color=never --max-columns=1000 --no-heading --line-number -v ^$```

When try search something (e.g., `mongodb.close`) it find few line with pattern (it is correct), but many lines without pattern, too.
No specific scenario, it is usual behavior.

**Comment by minad** [comment]
I don't see this issue in my setup. I suggest you use the default configuration without Orderless. Maybe the problem is due to the Orderless pattern compiler. I generally recommend that you prefer `consult-ripgrep` over `affe-grep`, since Affe is more experimental.

**Comment by damanis** [comment]
I tested both with Orderless and without - same result.
I know it's experimental, but it work better. `affe-find` I use as default instead of consult.

**Comment by minad** [comment]
On 6/29/23 15:08, damanis wrote:
> I tested both with Orderless and without - same result.
> I know it's experimental, but it work better. |affe-find| I use as
> default instead of consult.

Can you try a minimal configuration starting from emacs -Q?

**Comment by damanis** [comment]
The problem reproduced when I set `affe-count` to 1000 (some time there are many outputs).
