### ISSUE TITLE
affe-count limit

### ISSUE THREAD

**Issue by tpeacock19** [minad/affe#8]
More of a general question, but is there any downside to performance to increasing `affe-count`? I imagine this is the reason why it is limited to 20?

**Comment by minad** [comment]
The search will run until affe-count matches have been found. If you set a small value, it bails out faster. But you can experiment with other values to see how well it works for you. Does this answer your question?

**Comment by tpeacock19** [comment]
Yes, However I was just editing my comment to suggest adding to the indicator [# of matches / Total number of files/lines].

**Comment by minad** [comment]
You can try to add such a counter, I dislike that it will flicker a lot if showing the matches. So I probably won't add that.

**Comment by tpeacock19** [comment]
It would be more akin to fzf and useful when using `embark-export` for a larger number of matches, but I understand the hesitation. I'll look into a solution for myself.
