### ISSUE TITLE
fd is a lot faster!

### ISSUE THREAD

**Issue by bbuccianti** [minad/affe#9]
I'm using affe-find-command as "fd -HI -t f" (because I use a repository with .gitignore * on ~) and seems to work a lot faster than find. Maybe would be useful to provide it as an option?

**Comment by minad** [comment]
> Maybe would be useful to provide it as an option?

It already is provided as an option, isn't it? Just set `(setq affe-find-command "fd -HI -t f")` ;)

Seriously, I don't see that of a big difference, the fs cache matters a lot more it seems. I am happy with `find` as default.
